sudo: required
services:
  - docker

before_install:
  - docker build -t sumitdba10/multi-docker -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true sumitdba10/multi-docker npm run test

after_success:
  - docker build -t sumitdba10/multi-client ./client
  - docker build -t sumitdba10/multi-nginx ./nginx
  - docker build -t sumitdba10/multi-server ./server
  - docker build -t sumitdba10/multi-worker ./worker
  # Log into the docker CLI
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take those images and push to Docker Hub
  - docker push sumitdba10/multi-client
  - docker push sumitdba10/multi-nginx
  - docker push sumitdba10/multi-server
  - docker push sumitdba10/multi-worker
