sudo: required
services:
  - docker

before_install:
  - docker build -t sumitdba10/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sumitdba10/multi-docker npm test

after_success:
  - docker build -t sumitdba10/multi-client ./client
  - docker build -t sumitdba10/multi-nginx ./nginx
  - docker build -t sumitdba10/multi-server ./server
  - docker build -t sumitdba10/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take those images and push to Docker Hub
  - docker push sumitdba10/multi-client
  - docker push sumitdba10/multi-nginx
  - docker push sumitdba10/multi-server
  - docker push sumitdba10/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ca-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ca-central-1-463765748461
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY